version: '3.8'

services:
  postgres:
    image: postgres
    container_name: gold-business-db
    environment:
      POSTGRES_DB: gold-business
      POSTGRES_USER: LENOVO
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - webnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: elasticsearch-gold
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - webnet

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.0
    container_name: kibana-gold
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - webnet



networks:
  webnet:
