package com.mo.auth;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.oauth2.core.user.OAuth2User;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.mo.auth.totp.UserTotpSecret;
import com.mo.core.model.needs.AbstractUserNeed;
//import com.mo.core.model.organisations.Organisation;
import com.mo.core.model.organisations.OrganisationMember;

import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Entity
@Table(name = "users", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"email"})
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User implements UserDetails, OAuth2User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String fullName;

    private String email;
    
    private String phoneNumber;

    private String password;

    private Date createdAt;

    private Date updatedAt;
    
    /**
     * External wallet identifier generated by the wallet service.
     * This is an identifier only and not an access secret.
     */
    @Column(name = "external_wallet_id", unique = true)
    private String externalWalletId;

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(
        name = "user_roles",
        joinColumns = @JoinColumn(name = "user_id"),
        inverseJoinColumns = @JoinColumn(name = "role_id")
    )
    private List<Role> roles = new ArrayList<>();

    @ToString.Exclude
    @JsonBackReference
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonIgnore
    private List<OrganisationMember> memberships = new ArrayList<>();

    @ToString.Exclude
    @OneToOne(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private UserTotpSecret totpSecret;

    @ToString.Exclude
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<AbstractUserNeed> needs = new ArrayList<>();

//    @Lob
//    @Column(nullable = false)
    private String encryptedSecret;
    
    @Builder.Default
    private boolean totpEnabled = false;

    // Map des attributs OAuth2 (ex: name, email, etc.)
    @ToString.Exclude
    @Transient
    @JsonIgnore
    private Map<String, Object> attributes;

    public boolean hasRoleInOrganisation(Long organisationId, String role) {
        return memberships.stream()
            .filter(m -> m.getOrganisation().getId().equals(organisationId))
            .anyMatch(m -> m.getRoles().contains(role));
    }

    @Override
    @JsonIgnore
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return this.roles.stream()
            .map(role -> new SimpleGrantedAuthority("ROLE_" + role.getName().toUpperCase()))
            .collect(Collectors.toList());
    }

    @Override
    public String getUsername() {
        return this.email;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }

    // Implémentation spécifique à OAuth2User

    @Override
    public Map<String, Object> getAttributes() {
        return this.attributes;
    }

    public void setAttributes(Map<String, Object> attributes) {
        this.attributes = attributes;
    }

    @Override
    public String getName() {
        // retourne une clé unique pour l'utilisateur (souvent "sub" ou "email")
        return this.email;
    }
}