package com.mo.core.dtos.usersDtos;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
/**
 * UpdateExternalWalletIdRequest
 *
 * Purpose: DTO for updating a user's external wallet identifier. Used when the
 * user links or updates an external wallet connected to the platform.
 *
 * Fields:
 * - `externalWalletId` (String): identifier generated by the wallet service.
 *   This value is an external wallet reference, not an access secret.
 *
 * Frontend guidance:
 * - Treat this value as an identifier only; do not expose it as a secret.
 * - Validate it is non-empty before sending.
 * - Display confirmation once the wallet association is complete.
 */
public class UpdateExternalWalletIdRequest {
    @NotBlank
    private String externalWalletId;
}
